apiVersion: v1
kind: Service
metadata:
  name: penr-oz-openai
  labels:
    app: penr-oz-openai
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: penr-oz-openai
